.github/workflows/dns-preview.yml

Wrzuciłem na stałe commit hasha akcji do komentowania na pull requestach, usunąłem też zmienną która jest defaultowo ustawiona.

dns-preview.comment: lekkie zmiany

---

domains/zhp.pl.d/dolnoslaska.js

WIX requires both main domain and www to point directly to their domain to accept the domain. 
Also 3 other domains added for language-specific pages

Use WIX-specific settings for Polkowice

---

domains/zhp.pl.d/gdanska.js

Obecnie kwidzyn.zhp.pl  ma na ogicomie przekierowanie w JS na kwidzynzhp.pl (hostowany na netmark)
Od teraz kwidzyn.zhp.pl będzie kierować do netmarka, więc nie będzie przekierowania
Poczta w domenie kwidzyna nie jest obecnie skonfigurowana

Przenosimy kwidzyn na netmark

---

domains/zhp.pl.d/lubuska.js

- Dodanie delegacji A dla Hufca Żary (MS365-11045)
- usunięcie delegacji dla Sulęcina

Zmiany w Lubuskiej

---

domains/redirects/redirectFiles/zhp.pl.json
domains/zhp.pl.d/gdanska.js

Dotychczas Chorągiew Gdańska używała hostingu Cyberfolks
Chcemy jednak używać repozytorium, które jest wygodniejsze i zarządzane przez GK

Przenoszę gdanska.zhp.pl do repozytorium

---

domains/zhp.pl.d/wielkopolska.js

Na prośbę Zespołu promocji Chorągwi Wielkopolskiej oraz Biura Chorągwii tworzymy subdomenę wlkp.zhp.pl, do której sukcesywnie będziemy migrować strony internetowe.

Krok 0 migracji domeny Chorągwi Wielkopolskiej

---

domains/redirects/redirectFiles/zhp.pl.json

Przekierowanie zaproponowanę przez Kasię. Zmniejszy liczbę zgłoszeń o niedziałających deklaracjach (_informuje_, że teraz jest to w tipi)

Przekierowanie deklaracja -> tipi

---

.github/workflows/dns-push.yml

Currently, StackExchange has some issues with creating new docker images (they don't push them to the hub, CI issues). So I used less official image for new version of dnscontrol and it fixed

Update DNS control to 3.17

---

domains/zhp.pl.d/bialostocka.js

poprzedni administrator broi, bo go usunęliśmy z ZHP za treści, które propagował. na stronie teraz też wywiesił jakieś...

pilnie odpiąć lomze - poprzedni administrator broi

---

domains/zhp.pl.zone.js

Zgodnie z informacją od Martyny i Olgi - nie jest używane

Usuwam nieużywane mailing.zhp.pl

---

domains/zhp.pl.d/zachodniopomorska.js

Wraz ze zmianą NS'a musimy dodać slawno.zhp.pl jako domenę do M365, aby przepiąć skrzynki pocztowe na tę domenę.
Poprosiłbym o kontakt, żeby to skoordynować przed mergem.

Migracja 'slawno' na hosting chorągwiany

---

domains/zhp.pl.d/wielkopolska.js

Hufiec Turek chce podpiąć swoją domenę pod offica 365. Korzystają tylko ze strony, więc chce zamienić im delegację NS na delegację A i na repo użyć funkcji Ms365_Subdomain by odpowiednie rekordy ustawić.

Zmiany w DNS hufca Turek

---

domains/zhp.pl.d/stoleczna.js

Tymczasowa weryfikacja Google dla `arsenal.zhp.pl`, chwila moment i usuwam (ok. tydzień).

Hufiec Moko - Weryfikacja Google

---

domains/zhp.pl.d/stoleczna.js

Druga tymczasowa weryfikacja Google dla `arsenal.zhp.pl`, za ok. tydzień usunę.

Druga weryfikacja google dla `arsenal.zhp.pl`

---

domains/zhp.pl.d/kp.js

Zmiana NS na A w hufcach i bazach, delegacja pozostałych hufców (możliwych) do MS365, przeniesienie Chojnic na hosting chorągwi.

Many changes in kp.js

---

domains/functions/delegation.js
domains/zhp.pl.d/lubuska.js

Domena `nowasol` używa obecnie CNAME, aby podpiąć stronę z blogger.com.
Dodałem wsparcie dla wielu wpisów A i przepisałem domenę na delegację A zgodnie z https://support.google.com/blogger/answer/1233387?hl=en. To pozwoli mi dodać ich do MS365

Wsparcie dla wielu wpisów A oraz migracja Hufca Nowa Sól (MS365-35854)

---

domains/zhp.pl.d/wydzialy.js

Change arch.cbp.zhp.pl to cbp-arch.zhp.pl

Fix second level domain name for arch.cbp

---

domains/zhp.pl.d/kp.js

Hufiec Powiatu Wloclawskiego zmienia hosting na hosting choragwi, zmiana delegacji NS na A, dodatkowo delegacja domeny do MS365.

Przeniesienie Powiatu Wloclawskiego

---

domains/zhp.pl.d/kp.js

Hufiec Toruń dokonuje migracji z Atthost do Seohost, zmiana zgodnie ze zgłoszeniami MS365-42046 oraz MS365-42045. Zmiana wpisów NS na A, dodanie wpisu do MS365 (domena już dodana w MS365).

Migracja na nowy Hosting Hufca Toruń

---

domains/zhp.pl.d/kp.js

Przeniesienie stron baz chorągwi na drugi hosting wraz ze zmianą ich adresów z subdomeny chorągwi do domeny zhp.pl

Migracja stron baz w KP

---

domains/zhp.pl.d/wydzial-it.js

tipi.zhp.pl jako domena wysyłająca pocztę. mam dylemat czy dodawać tutaj MX bo on nie jest potrzebny do samej wysyłki ale dzięki temu będziemy dostawać zwrotki. Niestety w SPF i pośrednio w MX ujawniamy IP serwera.
Jak już będzie mailu zainstalowane to trzeba mu wygenerować klucz DKIM i dodać do rekordu.

tipi.zhp.pl sends email

---

domains/zhp.pl.d/wydzial-it.js

Dodałem CNAME do wersji produkcyjnej aplikacji statycznej csz-sfh-app, czyli do Centralnego Systemu Zgłoszeń Safe From Harm.

add cname for csz-sfh-app

---

domains/zhp.pl.d/wydzial-it.js

CNAME dla dev-sfh.zhp.pl, na której są buildy aplikacji z brancha development

add cname for dev-sfh.zhp.pl

---

domains/redirects/redirectFiles/zhp.pl.json
domains/zhp.pl.d/wydzial-it.js
domains/zhp.pl.d/wydzialy.js

dscz.zhp.pl - przekierowanie na azure static web app
swiatlo.zhp.pl - usuniecie delegacji na serwer i przekierowanie na zhp.pl/bsp

dscz.zhp.pl i swiatlo.zhp.pl
