itwzhp/infrastruktura

- domains/zhp.pl.zone.js
https://jira.zhp.pl/browse/MS365-7389
> delegation(MS365-7389): kolbuszowa.zhp.pl

- .github/actions-config/labeler.yml
- .github/workflows/labeler.yml
feature(labeler): add compontent/ACTIONS
and move labeler's config to seperate directory
> feature(labeler): add compontent/ACTIONS

- domains/zhp.pl.d/podkarpacka.js
- domains/zhp.pl.zone.js
move well-known podkarpacka's records to different file
delagate A record for mielec.zhp.pl
> move well-known podkarpacka's records to different file

- domains/dnsconfig.js
- domains/service-providers.js
- domains/zhp.net.pl.zone.js
- domains/zhp.pl.d/gdanska.js
- domains/zhp.pl.zone.js
- Remove 'morenka' domains
- Some refactor
> Remove 'morenka'

- domains/zhp.pl.d/gdanska.js
> Dodanie DNS Hufca Malbork

- domains/zhp.pl.d/krakowska.js
Requested by proper district commissioner.
> Switch krakowsrodmiescie to new server

- domains/zhp.pl.d/podkarpacka.js
> Przeniesienie Hufca Jarosław do Cyberfolks

- domains/zhp.pl.d/lodzka.js
migracja strony głównej Pabianic
> migracja Pabianic :)

- domains/zhp.pl.d/wielkopolska.js
Delegacja na razie na cele przekierowania, potem może zostanie przeniesiona strona na odpowiedni adres
Przy okazji dodaję komentarz do połowy domen, której najwyraźniej nie działają
> Delegacja wielkopolska.zhp.pl - MS365-13911

- domains/zhp.pl.d/slaska.js
Zmiana rekordów A dla hme.zhp.pl oraz wilczysko.zhp.pl
> Poprawione rekordy A

- domains/zhp.pl.d/slaska.js
> Zmiana delegacji cieszyn.zhp.pl.

- domains/zhp.pl.d/bialostocka.js
naprawa rekordu ktory popsul PR166
> fix lomza.zhp.pl@MS365 (#166)

- domains/zhp.pl.d/lodzka.js
> harcerskafantazjada (MS365-19895)

- domains/zhp.pl.d/bialostocka.js
później będzie przechrzczona domena, jak już zespoły uzupełnią nowy szablon
> development nowej strony białegostoku

- domains/zhp.pl.d/bialostocka.js
- domains/zhp.pl.d/mazowiecka.js
- domains/zhp.pl.d/stoleczna.js
- domains/zhp.pl.d/wydzial-it.js
Usuwam domeny nie działające lub przejęte
> Removing unused domains

- domains/zhp.pl.d/lubuska.js
Dodanie rekordów do zmiany domeny hufca Strzelecko-Drezdeneckiego
> Przygotowania do zmiany domeny hufca

- domains/zhp.pl.d/zachodniopomorska.js
Nie mogę na atthost odpalić certyfikatów Let's Encrypt. Zmiana z CNAME na A powinna pomóc
> Update zachpom subdomain records from CNAME to A

- .github/actions-config/labeler.yml
- domains/redirects/redirectFiles/zhp.net.pl.json
- domains/zhp.net.pl.zone.js
Nowy adres jest zgodny z instrukcją (w domenie hufca)
Dodajemy przekierowanie
> MS365-22613 - migacja zlotaosemka.zhp.net.pl

- domains/zhp.pl.d/gdanska.js
Po weryfikacji w OVH ten TXT zostanie usunięty
> Malbork - TXT do weryfikacji 

- domains/zhp.pl.d/krakowska.js
> Switch tarnow to the new server (accepted by district commissioner)

- domains/zhp.pl.d/zachodniopomorska.js
https://jira.zhp.pl/browse/MS365-25188
> Dodanie subdomeny poczta.szczecin.zhp.pl

- domains/zhp.pl.d/gdanska.js
Dodaję subdomenę dla backendu ewidencji sprzętu
> subdomena dla Gdańskiej

- domains/zhp.pl.d/wydzialy.js
przejęcie subdomeny, wycofuje i omijam review w konsultacji z naczelniczką
cc: @karol-gro @kowalczyk-p
> wycofanie delegacji subdomeny cwm

- domains/zhp.pl.d/dolnoslaska.js
Przenosiny na inny serwer z Nazwy na Cyberfolks  wpisy MX popoprawiam po przenosinych
> Pilne przeniesienie na inny serwer

- domains/zhp.pl.d/wydzialy.js
we współpracy z wkip, potrzebujemy testową stronę, wystawię przestrzeń na plesku
> add simson's test site

- domains/zhp.pl.d/wydzialy.js
> update simson's test site

- domains/zhp.pl.d/wydzial-it.js
Add beta.zhp.pl as temporary new zhp.pl site on plesk server
> Add beta.zhp.pl on plesk

- domains/1procent.pl.zone.js
- domains/bikejamboree.pl.zone.js
- domains/redirects/redirectFiles/zhp.pl.json
- domains/zhp.net.pl.zone.js
- domains/zhp.pl.d/gdanska.js
- domains/zhp.pl.d/redirects.js
- domains/zhp.pl.d/wm.js
- domains/zhp.pl.d/wydzial-it.js
- domains/zhp.pl.zone.js
Sprawdźcie czy niczego nie popieprzyłem
> Add Cloudflare proxy to all plesk sites

- domains/redirects/redirectFiles/zhp.pl.json
> Fix dokumenty.zhp.pl

- domains/redirects/redirectFiles/zhp.pl.json
- domains/zhp.pl.d/wydzial-it.js
Move from proxy redirect ot azure functions
> Add redirect for helpdesk.zhp.pl in Azure functions

- .github/tests.ps1
- domains/zhp.pl.d/wydzial-it.js
Wygląda na błąd przy kopiowaniu wpisów DKIM
@kowalczyk-p - rzuć okiem czy to nie powinno być w ten sposób, zauważyłem przy okazji
> poprawka DKIM dla mail-auto

- domains/zhp.pl.d/wm.js
mazurski, baldy, olsztyn - delegacja A
> MS365-44428, MS365-44451, MS365-44426

- domains/redirects/redirectFiles/zhp.pl.json
Przekierowanie z helpdeskgk.zhp.pl do Jira GK ZHP dla pracowników i członków GK
> add redirect helpdeskgk.zhp.pl

- domains/zhp.pl.d/gdanska.js
> Zmiana delegacji sprzet.gdanska

- .github/workflows/dns-build.yml
- .github/workflows/dns-preview.yml
- .github/workflows/dns-push.yml
- .github/workflows/redirects-push.yml
- .github/workflows/redirects-test.yml
* Bump all actions to newest version
> Bump all actions to newest version (#325)

- domains/redirects/redirectFiles/zhp.pl.json
Na wniosek autora strony - zakończenie projektu.
> Usunięcie przekierowania sprawności.gdanska

- domains/zhp.pl.d/kp.js
Dodanie delegacji dla baz Roscimin oraz Gaj w związku z przygotowaniem do przeniesienia stron pod produkcyjny adres.
> Add Gaj and Roscimin delegation
